# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "nirvana-rust"
version = "0.0.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2021"
publish = false

[features]
strict = []

[dependencies]
byteordered = "0.6.0"
clap = { version = "3.2.19", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
