# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Test
on: [push, pull_request]
jobs:
  fmt:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-24
          profile: minimal
          components: rustfmt
          override: true
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy --locked --all-targets --features strict

  test:
    if: 'false' # Disable in CI since it requires a copy of the game files
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --locked --no-run
      - run: cargo test --locked
